import type { ChapterDefinition } from "./types";

const sixth = 1 / 6;

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: "origin",
    index: 0,
    title: "Origin",
    statement: "Aether is the space between all things.",
    fragment:
      "In the beginning was the word, and the word was a pattern — a point defined by everything it might touch.",
    range: [0, sixth],
    camera: { position: [0.25, 0.28, 11.9], target: [0.15, 0, -0.45], fov: 42 },
    palette: {
      void: "#020207",
      primary: "#62d7ff",
      secondary: "#8757ff",
      accent: "#ffc66d",
    },
    simulation: {
      birth: 0.28,
      tension: 0.08,
      order: 0.12,
      collapse: 0,
      emergence: 0,
      pointerForce: 0.3,
    },
    visual: {
      membraneOpacity: 0.58,
      membraneScale: 0.82,
      contourDensity: 0.28,
      particleDensity: 0.34,
      stressIntensity: 0.34,
      collapseDistortion: 0,
      cameraProximity: 0.18,
      ribbonDepth: 0.36,
      nestedScale: 0.34,
    },
    post: { bloom: 0.7, aberration: 0.0001, vignette: 0.72, depthOfField: 0.18 },
  },
  {
    id: "tension",
    index: 1,
    title: "Tension",
    statement: "Lattice Tension is the hidden pressure of connection.",
    fragment:
      "Every bond is a negotiation between distance and the memory of being near.",
    range: [sixth, sixth * 2],
    camera: { position: [-1.35, 0.62, 7.8], target: [0.45, 0.05, -0.2], fov: 48 },
    palette: {
      void: "#020207",
      primary: "#7b78ff",
      secondary: "#ff4fd8",
      accent: "#ff9a4f",
    },
    simulation: {
      birth: 0.8,
      tension: 0.95,
      order: 0.28,
      collapse: 0,
      emergence: 0.05,
      pointerForce: 0.82,
    },
    visual: {
      membraneOpacity: 0.92,
      membraneScale: 1.08,
      contourDensity: 0.52,
      particleDensity: 0.72,
      stressIntensity: 1,
      collapseDistortion: 0.12,
      cameraProximity: 0.82,
      ribbonDepth: 0.82,
      nestedScale: 0.52,
    },
    post: { bloom: 0.96, aberration: 0.0004, vignette: 0.68, depthOfField: 0.55 },
  },
  {
    id: "pattern",
    index: 2,
    title: "Pattern",
    statement: "Every point pulls. Every line remembers.",
    fragment:
      "Pattern is not repetition. It is difference learning how to remain connected.",
    range: [sixth * 2, sixth * 3],
    camera: { position: [1.85, 1.15, 10.6], target: [0, 0.15, -1], fov: 45 },
    palette: {
      void: "#010408",
      primary: "#2fffc3",
      secondary: "#00a8ff",
      accent: "#eaff5e",
    },
    simulation: {
      birth: 1,
      tension: 0.48,
      order: 1,
      collapse: 0,
      emergence: 0.18,
      pointerForce: 0.55,
    },
    visual: {
      membraneOpacity: 0.78,
      membraneScale: 1,
      contourDensity: 1,
      particleDensity: 0.86,
      stressIntensity: 0.68,
      collapseDistortion: 0.06,
      cameraProximity: 0.46,
      ribbonDepth: 0.72,
      nestedScale: 1,
    },
    post: { bloom: 1.02, aberration: 0.0005, vignette: 0.62, depthOfField: 0.38 },
  },
  {
    id: "collapse",
    index: 3,
    title: "Collapse",
    statement: "What breaks does not disappear. It changes relation.",
    fragment:
      "A system folding inward may be ending, or merely discovering another dimension.",
    range: [sixth * 3, sixth * 4],
    camera: { position: [0.35, -0.25, 6.4], target: [0.15, 0.05, 0.2], fov: 52 },
    palette: {
      void: "#050108",
      primary: "#ff3b5c",
      secondary: "#ff7a2f",
      accent: "#ffd166",
    },
    simulation: {
      birth: 1,
      tension: 0.88,
      order: 0.18,
      collapse: 1,
      emergence: 0,
      pointerForce: 0.9,
    },
    visual: {
      membraneOpacity: 0.66,
      membraneScale: 0.7,
      contourDensity: 0.42,
      particleDensity: 0.64,
      stressIntensity: 0.94,
      collapseDistortion: 1,
      cameraProximity: 1,
      ribbonDepth: 0.88,
      nestedScale: 0.22,
    },
    post: { bloom: 1.18, aberration: 0.0017, vignette: 0.8, depthOfField: 0.72 },
  },
  {
    id: "emergence",
    index: 4,
    title: "Emergence",
    statement: "The universe is not still. It is breathing.",
    fragment:
      "Nothing returns unchanged. The new form carries the pressure that made it possible.",
    range: [sixth * 4, sixth * 5],
    camera: { position: [-1.9, 0.95, 9.15], target: [0.25, 0.1, -0.6], fov: 46 },
    palette: {
      void: "#010604",
      primary: "#ffd75e",
      secondary: "#36ffa0",
      accent: "#b7ffe9",
    },
    simulation: {
      birth: 1,
      tension: 0.35,
      order: 0.7,
      collapse: 0.22,
      emergence: 1,
      pointerForce: 0.62,
    },
    visual: {
      membraneOpacity: 0.96,
      membraneScale: 1.14,
      contourDensity: 0.92,
      particleDensity: 1,
      stressIntensity: 0.84,
      collapseDistortion: 0.18,
      cameraProximity: 0.58,
      ribbonDepth: 1,
      nestedScale: 0.9,
    },
    post: { bloom: 1.16, aberration: 0.00065, vignette: 0.56, depthOfField: 0.42 },
  },
  {
    id: "aether",
    index: 5,
    title: "Aether",
    statement: "The answer is not a number. It is a pattern.",
    fragment:
      "The answer was never a thing to be held — it is blowing in the wind, an agreement to keep becoming.",
    range: [sixth * 5, 1],
    camera: { position: [0.15, 0.42, 12.4], target: [0.05, 0.05, -0.8], fov: 48 },
    palette: {
      void: "#030109",
      primary: "#cfa9ff",
      secondary: "#5ee4ff",
      accent: "#fff6ff",
    },
    simulation: {
      birth: 1,
      tension: 0.46,
      order: 0.88,
      collapse: 0,
      emergence: 1,
      pointerForce: 0.48,
    },
    visual: {
      membraneOpacity: 1,
      membraneScale: 1.28,
      contourDensity: 0.62,
      particleDensity: 1,
      stressIntensity: 0.92,
      collapseDistortion: 0,
      cameraProximity: 0.3,
      ribbonDepth: 0.94,
      nestedScale: 1,
    },
    post: { bloom: 1.24, aberration: 0.00035, vignette: 0.52, depthOfField: 0.26 },
  },
];

export const PHILOSOPHICAL_FRAGMENTS = CHAPTERS.map((chapter) => chapter.fragment);
