import type { ChapterDefinition } from "./types";
import { CHAPTER_SIGNATURES } from "./signatures";

const sixth = 1 / 6;

function withSignature(
  chapter: Omit<ChapterDefinition, "signature">,
): ChapterDefinition {
  return {
    ...chapter,
    signature: CHAPTER_SIGNATURES[chapter.id],
  };
}

export const CHAPTERS: ChapterDefinition[] = [
  withSignature({
    id: "origin",
    index: 0,
    title: "Origin",
    statement: "Aether is the space between all things.",
    fragment:
      "In the beginning was the word, and the word was a pattern — a point defined by everything it might touch.",
    range: [0, sixth],
    camera: { position: [0.25, 0.28, 11.9], target: [0.15, 0, -0.45], fov: 42 },
    palette: {
      void: "#020208",
      primary: "#00f0ff",
      secondary: "#10b981",
      accent: "#fcd34d",
    },
    simulation: {
      birth: 0.28,
      tension: 0.05,
      order: 0.12,
      collapse: 0,
      emergence: 0,
      pointerForce: 0.2,
      resonance: 0.05,
      interference: 0.05,
      singularity: 0.02,
      diffusion: 0.08,
      curvature: 0.04,
      scale: 1.0,
    },
    visual: {
      membraneOpacity: 0.58,
      membraneScale: 0.82,
      contourDensity: 0.28,
      particleDensity: 0.34,
      stressIntensity: 0.34,
      collapseDistortion: 0,
      cameraProximity: 0.18,
      ribbonDepth: 0.36,
      nestedScale: 0.34,
    },
    post: { bloom: 0.7, aberration: 0.0001, vignette: 0.72, depthOfField: 0.18 },
  }),
  withSignature({
    id: "tension",
    index: 1,
    title: "Tension",
    statement: "Lattice Tension is the hidden pressure of connection.",
    fragment:
      "Every bond is a negotiation between distance and the memory of being near.",
    range: [sixth, sixth * 2],
    camera: { position: [-1.35, 0.62, 7.8], target: [0.45, 0.05, -0.2], fov: 48 },
    palette: {
      void: "#04000b",
      primary: "#ff2a8d",
      secondary: "#6366f1",
      accent: "#f43f5e",
    },
    simulation: {
      birth: 0.8,
      tension: 1.45,
      order: 0.28,
      collapse: 0,
      emergence: 0.05,
      pointerForce: 0.95,
      resonance: 0.55,
      interference: 0.25,
      singularity: 0.08,
      diffusion: 0.18,
      curvature: 0.25,
      scale: 1.2,
    },
    visual: {
      membraneOpacity: 0.92,
      membraneScale: 1.08,
      contourDensity: 0.52,
      particleDensity: 0.72,
      stressIntensity: 1,
      collapseDistortion: 0.12,
      cameraProximity: 0.82,
      ribbonDepth: 0.82,
      nestedScale: 0.52,
    },
    post: { bloom: 0.96, aberration: 0.0004, vignette: 0.68, depthOfField: 0.55 },
  }),
  withSignature({
    id: "pattern",
    index: 2,
    title: "Pattern",
    statement: "Every point pulls. Every line remembers.",
    fragment:
      "Pattern is not repetition. It is difference learning how to remain connected.",
    range: [sixth * 2, sixth * 3],
    camera: { position: [1.85, 1.15, 10.6], target: [0, 0.15, -1], fov: 45 },
    palette: {
      void: "#01050a",
      primary: "#adff2f",
      secondary: "#00ffff",
      accent: "#ffffff",
    },
    simulation: {
      birth: 1,
      tension: 0.3,
      order: 1,
      collapse: 0,
      emergence: 0.18,
      pointerForce: 0.4,
      resonance: 0.35,
      interference: 0.15,
      singularity: 0.05,
      diffusion: 0.22,
      curvature: 0.9,
      scale: 0.85,
    },
    visual: {
      membraneOpacity: 0.78,
      membraneScale: 1,
      contourDensity: 1,
      particleDensity: 0.86,
      stressIntensity: 0.68,
      collapseDistortion: 0.06,
      cameraProximity: 0.46,
      ribbonDepth: 0.72,
      nestedScale: 1,
    },
    post: { bloom: 1.02, aberration: 0.0005, vignette: 0.62, depthOfField: 0.38 },
  }),
  withSignature({
    id: "collapse",
    index: 3,
    title: "Collapse",
    statement: "What breaks does not disappear. It changes relation.",
    fragment:
      "A system folding inward may be ending, or merely discovering another dimension.",
    range: [sixth * 3, sixth * 4],
    camera: { position: [0.35, -0.25, 6.4], target: [0.15, 0.05, 0.2], fov: 52 },
    palette: {
      void: "#070102",
      primary: "#ff3e00",
      secondary: "#9b0000",
      accent: "#ffd700",
    },
    simulation: {
      birth: 1,
      tension: 0.9,
      order: 0.18,
      collapse: 1,
      emergence: 0,
      pointerForce: 1.2,
      resonance: 0.82,
      interference: 0.35,
      singularity: 0.55,
      diffusion: 0.15,
      curvature: 1.3,
      scale: 0.6,
    },
    visual: {
      membraneOpacity: 0.66,
      membraneScale: 0.7,
      contourDensity: 0.42,
      particleDensity: 0.64,
      stressIntensity: 0.94,
      collapseDistortion: 1,
      cameraProximity: 1,
      ribbonDepth: 0.88,
      nestedScale: 0.22,
    },
    post: { bloom: 1.18, aberration: 0.0017, vignette: 0.8, depthOfField: 0.72 },
  }),
  withSignature({
    id: "emergence",
    index: 4,
    title: "Emergence",
    statement: "The universe is not still. It is breathing.",
    fragment:
      "Nothing returns unchanged. The new form carries the pressure that made it possible.",
    range: [sixth * 4, sixth * 5],
    camera: { position: [-1.9, 0.95, 9.15], target: [0.25, 0.1, -0.6], fov: 46 },
    palette: {
      void: "#000603",
      primary: "#00ff88",
      secondary: "#ff7700",
      accent: "#e2f3e5",
    },
    simulation: {
      birth: 1,
      tension: 0.7,
      order: 0.7,
      collapse: 0.22,
      emergence: 1,
      pointerForce: 0.85,
      resonance: 0.68,
      interference: 0.42,
      singularity: 0.18,
      diffusion: 0.55,
      curvature: 0.15,
      scale: 1.4,
    },
    visual: {
      membraneOpacity: 0.96,
      membraneScale: 1.14,
      contourDensity: 0.92,
      particleDensity: 1,
      stressIntensity: 0.84,
      collapseDistortion: 0.18,
      cameraProximity: 0.58,
      ribbonDepth: 1,
      nestedScale: 0.9,
    },
    post: { bloom: 1.16, aberration: 0.00065, vignette: 0.56, depthOfField: 0.42 },
  }),
  withSignature({
    id: "aether",
    index: 5,
    title: "Aether",
    statement: "The answer is not a number. It is a pattern.",
    fragment:
      "The answer was never a thing to be held — it is blowing in the wind, an agreement to keep becoming.",
    range: [sixth * 5, 1],
    camera: { position: [0.15, 0.42, 12.4], target: [0.05, 0.05, -0.8], fov: 48 },
    palette: {
      void: "#03010b",
      primary: "#b886ff",
      secondary: "#00d9ff",
      accent: "#ff99bb",
    },
    simulation: {
      birth: 1,
      tension: 0.2,
      order: 0.88,
      collapse: 0,
      emergence: 1,
      pointerForce: 0.5,
      resonance: 0.92,
      interference: 0.1,
      singularity: 0.05,
      diffusion: 0.15,
      curvature: 0.08,
      scale: 1.05,
    },
    visual: {
      membraneOpacity: 1,
      membraneScale: 1.28,
      contourDensity: 0.62,
      particleDensity: 1,
      stressIntensity: 0.92,
      collapseDistortion: 0,
      cameraProximity: 0.3,
      ribbonDepth: 0.94,
      nestedScale: 1,
    },
    post: { bloom: 1.24, aberration: 0.00035, vignette: 0.52, depthOfField: 0.26 },
  }),
  withSignature({
    id: "interference",
    index: 6,
    title: "Interference",
    statement: "Every crossing leaves a trace that was not there before.",
    fragment: "Interference is not noise. It is the lattice learning the shape of its own questions.",
    range: [1.0, 1.166],
    camera: { position: [0.8, 0.5, 9.5], target: [0.1, 0.1, -0.3], fov: 47 },
    palette: {
      void: "#020005",
      primary: "#1df914",
      secondary: "#b026ff",
      accent: "#ff3366",
    },
    simulation: {
      birth: 0.9,
      tension: 1.1,
      order: 0.55,
      collapse: 0.15,
      emergence: 0.25,
      pointerForce: 0.75,
      resonance: 0.75,
      interference: 0.95,
      singularity: 0.1,
      diffusion: 0.35,
      curvature: 0.6,
      scale: 1.15,
    },
    visual: {
      membraneOpacity: 0.88,
      membraneScale: 1.05,
      contourDensity: 0.98,
      particleDensity: 0.82,
      stressIntensity: 0.88,
      collapseDistortion: 0.18,
      cameraProximity: 0.55,
      ribbonDepth: 0.78,
      nestedScale: 0.82,
    },
    post: { bloom: 1.08, aberration: 0.0009, vignette: 0.58, depthOfField: 0.48 },
  }),
  withSignature({
    id: "singularity",
    index: 7,
    title: "Singularity",
    statement: "At the center, relation becomes absolute.",
    fragment: "What falls in does not vanish. It becomes the question the lattice asks of itself.",
    range: [1.166, 1.333],
    camera: { position: [0.1, -0.4, 5.8], target: [0.05, 0.02, 0.35], fov: 54 },
    palette: {
      void: "#000000",
      primary: "#00e1ff",
      secondary: "#ff0055",
      accent: "#ffae00",
    },
    simulation: {
      birth: 0.6,
      tension: 1.8,
      order: 0.22,
      collapse: 0.98,
      emergence: 0.08,
      pointerForce: 1.6,
      resonance: 0.92,
      interference: 0.25,
      singularity: 0.98,
      diffusion: 0.12,
      curvature: 2.0,
      scale: 0.45,
    },
    visual: {
      membraneOpacity: 0.72,
      membraneScale: 0.68,
      contourDensity: 0.48,
      particleDensity: 0.58,
      stressIntensity: 0.98,
      collapseDistortion: 0.98,
      cameraProximity: 0.95,
      ribbonDepth: 0.92,
      nestedScale: 0.28,
    },
    post: { bloom: 1.32, aberration: 0.0022, vignette: 0.88, depthOfField: 0.78 },
  }),
  withSignature({
    id: "quantum",
    index: 8,
    title: "Quantum Fold",
    statement: "Beneath the continuous lies the fold that chooses.",
    fragment: "The smallest pattern still pulls. Its memory is the first tension.",
    range: [1.333, 1.5],
    camera: { position: [-0.6, 0.35, 8.2], target: [-0.05, 0.08, -0.55], fov: 44 },
    palette: {
      void: "#010307",
      primary: "#f032e6",
      secondary: "#00face",
      accent: "#fff200",
    },
    simulation: {
      birth: 0.95,
      tension: 0.1,
      order: 0.28,
      collapse: 0.05,
      emergence: 0.42,
      pointerForce: 0.9,
      resonance: 0.68,
      interference: 0.88,
      singularity: 0.15,
      diffusion: 0.72,
      curvature: 0.85,
      scale: 4.5,
    },
    visual: {
      membraneOpacity: 0.82,
      membraneScale: 0.78,
      contourDensity: 0.92,
      particleDensity: 0.95,
      stressIntensity: 0.65,
      collapseDistortion: 0.08,
      cameraProximity: 0.42,
      ribbonDepth: 0.65,
      nestedScale: 0.95,
    },
    post: { bloom: 0.95, aberration: 0.00055, vignette: 0.48, depthOfField: 0.32 },
  }),
  withSignature({
    id: "nebula",
    index: 9,
    title: "Nebula Veil",
    statement: "The largest patterns breathe slowest.",
    fragment: "Stars are not points. They are slow negotiations written in gas and gravity.",
    range: [1.5, 1.666],
    camera: { position: [1.2, 0.75, 11.8], target: [0.08, 0.12, -0.7], fov: 49 },
    palette: {
      void: "#010204",
      primary: "#ffd700",
      secondary: "#2563eb",
      accent: "#ff73b9",
    },
    simulation: {
      birth: 0.72,
      tension: 0.15,
      order: 0.65,
      collapse: 0.12,
      emergence: 0.98,
      pointerForce: 0.3,
      resonance: 0.88,
      interference: 0.42,
      singularity: 0.08,
      diffusion: 0.98,
      curvature: 0.02,
      scale: 0.5,
    },
    visual: {
      membraneOpacity: 0.95,
      membraneScale: 1.18,
      contourDensity: 0.35,
      particleDensity: 0.98,
      stressIntensity: 0.78,
      collapseDistortion: 0.15,
      cameraProximity: 0.48,
      ribbonDepth: 1.05,
      nestedScale: 1.25,
    },
    post: { bloom: 1.15, aberration: 0.00028, vignette: 0.42, depthOfField: 0.55 },
  }),
  withSignature({
    id: "echo",
    index: 10,
    title: "Echo",
    statement: "The aether does not forget the one who pressed.",
    fragment: "What you leave here changes what returns. The pattern now contains your question.",
    range: [1.666, 1.833],
    camera: { position: [0.05, 0.28, 14.2], target: [0.02, 0.03, -0.95], fov: 46 },
    palette: {
      void: "#060408",
      primary: "#ff82c3",
      secondary: "#a7f3d0",
      accent: "#a5b4fc",
    },
    simulation: {
      birth: 0.85,
      tension: 0.25,
      order: 0.78,
      collapse: 0.02,
      emergence: 0.95,
      pointerForce: 0.6,
      resonance: 1.15,
      interference: 0.55,
      singularity: 0.12,
      diffusion: 0.65,
      curvature: 0.4,
      scale: 1.25,
    },
    visual: {
      membraneOpacity: 0.98,
      membraneScale: 1.32,
      contourDensity: 0.58,
      particleDensity: 0.92,
      stressIntensity: 0.85,
      collapseDistortion: 0.02,
      cameraProximity: 0.22,
      ribbonDepth: 1.12,
      nestedScale: 1.35,
    },
    post: { bloom: 1.28, aberration: 0.00018, vignette: 0.38, depthOfField: 0.35 },
  }),
  withSignature({
    id: "origin_core",
    index: 11,
    title: "Origin Core",
    statement: "The soft beginning pulses eternal.",
    fragment:
      "Every descent ends where it began — not as repetition, but as recognition. The lattice remembers the first breath.",
    range: [1.833, 2.0],
    camera: { position: [0.2, 0.25, 13.5], target: [0.0, 0.0, -0.4], fov: 38 },
    palette: {
      void: "#010103",
      primary: "#10b981",
      secondary: "#f59e0b",
      accent: "#ffffff",
    },
    simulation: {
      birth: 0.95,
      tension: 0.1,
      order: 0.15,
      collapse: 0.0,
      emergence: 0.9,
      pointerForce: 0.4,
      resonance: 0.5,
      interference: 0.15,
      singularity: 0.03,
      diffusion: 0.25,
      curvature: 0.1,
      scale: 0.9,
    },
    visual: {
      membraneOpacity: 0.7,
      membraneScale: 0.9,
      contourDensity: 0.2,
      particleDensity: 0.5,
      stressIntensity: 0.3,
      collapseDistortion: 0.0,
      cameraProximity: 0.1,
      ribbonDepth: 0.3,
      nestedScale: 0.6,
    },
    post: { bloom: 0.75, aberration: 0.0001, vignette: 0.65, depthOfField: 0.15 },
  }),
];

export const PHILOSOPHICAL_FRAGMENTS = CHAPTERS.map((chapter) => chapter.fragment);
