uniform float uTime;
uniform float uTension;
uniform vec2 uMouse;
uniform float uPull;
uniform float uPulseX;
uniform float uPulseY;
uniform float uPulseStrength;
attribute float phase;
varying float vStress;
varying float vPhase;
varying float vFresnel;
void main() {
  vec3 pos = position;
  vec3 toC = -pos;
  float d = length(toC) + 0.0001;
  vec3 dir = toC / d;
  pos += dir * (uTension * 0.22 + uPull * 0.08);
  vec3 mDir = vec3(uMouse.x * 1.8, uMouse.y * 1.2, 0.0);
  pos += mDir * uPull * 0.07;
  vec3 pulsePos = vec3(uPulseX * 4.0, uPulseY * 3.0, 0.0);
  vec3 pDir = pos - pulsePos;
  float pd = length(pDir) + 0.001;
  pos -= normalize(pDir) * uPulseStrength * 0.35 * exp(-pd * 1.8);
  float damp = 1.0 - uTension * 0.6;
  pos.x += sin(uTime * 1.2 + phase) * 0.035 * damp;
  pos.z += cos(uTime * 1.1 + phase) * 0.035 * damp;
  float curl = uTension * 0.04 * sin(phase * 5.0 + uTime * 0.8);
  pos += vec3(sin(phase * 3.0), 0.0, cos(phase * 4.0)) * curl;
  float waveType = uTension;
  float globalWave = sin(uTime * 0.4 + length(pos) * 0.15) * waveType * 0.085;
  pos += normalize(pos) * globalWave;
  float vibFreq = 8.0 + uTension * 25.0;
  float vibration = sin(uTime * vibFreq + phase * 2.0) * waveType * 0.042;
  pos += vec3(0.0, vibration, 0.0);
  float twist = uTension * 0.19 * sin(uTime * 0.6 + pos.y * 0.4 + phase);
  float cs = cos(twist);
  float sn = sin(twist);
  float tx = pos.x * cs - pos.z * sn;
  float tz = pos.x * sn + pos.z * cs;
  pos.x = tx;
  pos.z = tz;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
  vStress = uTension;
  vPhase = phase;
  vec3 viewDir = normalize((modelViewMatrix * vec4(pos, 1.0)).xyz);
  vFresnel = pow(1.0 - abs(dot(normalize(pos), viewDir)), 2.0);
}