uniform float uTime;
uniform float uTension;
uniform vec2 uMouse;
uniform float uPull;
uniform float uPulseX;
uniform float uPulseY;
uniform float uPulseStrength;
attribute float nodePhase;
varying float vHeat;
varying vec3 vNormal;
varying float vFres;
void main() {
  vec3 pos = position;
  vec3 instanceOffset = vec3(instanceMatrix[3][0], instanceMatrix[3][1], instanceMatrix[3][2]);
  pos += instanceOffset;
  vec3 toC = -pos;
  float d = length(toC) + 0.0001;
  pos += (toC / d) * (uTension * 0.3 + uPull * 0.1);
  pos.x += uMouse.x * uPull * 0.75;
  pos.y += uMouse.y * uPull * 0.6;
  vec3 pulsePos = vec3(uPulseX * 4.0, uPulseY * 3.0, 0.0);
  vec3 pDir = pos - pulsePos;
  float pd = length(pDir) + 0.001;
  pos -= normalize(pDir) * uPulseStrength * 0.3 * exp(-pd * 1.6);
  float damp = 1.0 - uTension * 0.6;
  pos.x += sin(uTime * 1.2 + nodePhase) * 0.04 * damp;
  pos.z += cos(uTime * 1.1 + nodePhase) * 0.04 * damp;
  pos += normalize(vec3(sin(nodePhase*4.0), cos(nodePhase*3.0), sin(nodePhase*5.0))) * uTension * 0.025;
  float waveType = uTension;
  float globalWave = sin(uTime * 0.35 + length(pos) * 0.12) * waveType * 0.068;
  pos += normalize(pos) * globalWave;
  float vibFreq = 7.0 + uTension * 22.0;
  float vibration = sin(uTime * vibFreq + nodePhase * 1.8) * waveType * 0.034;
  pos += vec3(vibration * 0.6, vibration, vibration * 0.4);
  float twist = uTension * 0.16 * sin(uTime * 0.5 + pos.y * 0.3 + nodePhase);
  float cs = cos(twist);
  float sn = sin(twist);
  float tx = pos.x * cs - pos.z * sn;
  float tz = pos.x * sn + pos.z * cs;
  pos.x = tx;
  pos.z = tz;
  vec4 mvPosition = modelViewMatrix * vec4(pos, 1.0);
  vHeat = uTension * 0.6 + sin(uTime * 3.0 + nodePhase) * 0.3;
  vNormal = normalize(normalMatrix * normal);
  vec3 viewDir = normalize(-mvPosition.xyz);
  vFres = pow(1.0 - max(dot(vNormal, viewDir), 0.0), 3.0);
  gl_Position = projectionMatrix * mvPosition;
}